urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'repertoire.ui.views.home', name='home'),
    url(r'^lastfm-import$', 'repertoire.ui.views.lastfm_import'),
    url(r'^lastfm-import-artists$', 'repertoire.ui.views.lastfm_import_artists'),
    url(r'^albums$', 'repertoire.ui.views.albums'),
    url(r'^artist/add$', 'repertoire.ui.views.add_artist', name='add_artist'),
    url(r'^artist/([^/]+)$', 'repertoire.ui.views.view_artist'),
    url(r'^get-artist-data$', 'repertoire.ui.views.get_artist_data'),
    # url(r'^repertoire/', include('repertoire.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

ui/models.py
from django.db import models
from django.template.defaultfilters import slugify
import math
def erf(x):
    # save the sign of x
    sign = 1 if x >= 0 else -1
    x = abs(x)

    # constants
    a1 =  0.254829592
    a2 = -0.284496736
    a3 =  1.421413741
    a4 = -1.453152027
    a5 =  1.061405429
    p  =  0.3275911

    # A&S formula 7.1.26
    t = 1.0/(1.0 + p*x)
    y = 1.0 - (((((a5*t + a4)*t) + a3)*t + a2)*t + a1)*t*math.exp(-x*x)
    return sign*y

class ScrapeReq(models.Model):
    url = models.URLField(unique=True)
    priority = models.IntegerField()
    fulfilled = models.BooleanField()
    result = models.TextField()
    requested = models.DateField(null=True)

class Artist(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Artist, self).save(*args, **kwargs)
    
    # allmusic.com
    allmusic_name = models.CharField(max_length=200)
    allmusic_bio = models.TextField()

ALBUM_STATE_CHOICES = (
    ('w', 'wanted'),
    ('u', 'unclassified'),
    ('i', 'ignored'),
    ('g', 'grabbed'),
    ('d', 'downloaded'),
)
class Album(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Album, self).save(*args, **kwargs)
    
    artist = models.ForeignKey('Artist')
    state = models.CharField(choices=ALBUM_STATE_CHOICES, max_length=2, default='u')
    
    # allmusic.com
    allmusic_rating = models.IntegerField(default=-1)
    allmusic_pick = models.BooleanField(default=False)
    
    # rateyourmusic.com
    rym_year = models.IntegerField(default=0)
    rym_numratings = models.IntegerField(default=0)
    rym_numreviews = models.IntegerField(default=0)
    
    rym_overall = models.FloatField(default=0)
    rym_rating = models.IntegerField(default=0)
    rym_popularity = models.IntegerField(default=0)
    
    def combinedscore(self):
        
        # So a 5 on rym is roughly equal to a 6 on allmusic
        # a 4 ~ 4.5
        # 3.8 ~ 4
        # 3.5 ~ 3
        
        if self.rym_overall:
            rym = erf(self.rym_overall - 3.4)*3 + 3 #1 + self.rym_overall
        else:
            rym = None
        
        if self.allmusic_rating != -1:
            alm = self.allmusic_rating
        else:
            alm = None
        
        if rym == None and alm == None:
            return 0.0
        if rym == None:
            rym = alm
        if alm == None:
            alm = rym
        
        return math.sqrt(rym * alm)

class Track(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Track, self).save(*args, **kwargs)
    
    album = models.ForeignKey('Album')

ui/views.py
from django.shortcuts import render_to_response, redirect
from ui.models import *
from django.db import models
from django.template.defaultfilters import slugify
import scraper
import re
import threading
import lastfm
import django

def tmpl(n, **others):
    return render_to_response(n, dict({
        'artists': Artist.objects.all(),
        'albums': Album.objects.all(),
        'tracks': Track.objects.all(),
    }.items() + others.items()))

def home(req):
    print Artist.objects.count()
    return tmpl('home.html')

def albums(req):
    return tmpl('albums.html')

def add_artist(req):
    print req.POST['name']
    a = Artist(name=req.POST['name'])
    a.save()
    return redirect('/')

def lastfm_import(req):
    artists = lastfm.getArtists(req.POST['name'])
    artists = [a for a,c in artists if c > 2 and '/' not in a and ',' not in a and '&' not in a]
    # r = '<br>'.join(artists)
    
    return tmpl('lastfm_artist_importer.html', artistnames=artists)
    # return django.http.HttpResponse(r)
def lastfm_import_artists(req):
    artistnames = [p for p in req.POST if req.POST[p] == 'on']
    for a in artistnames:
        try:
            ar = Artist.objects.get(slug=slugify(a))
        except Artist.DoesNotExist:
            ar = Artist(name=a)
            ar.save()
    return redirect('/')

artist_thread = None
def reload_artists():
    global artist_thread
    print 'STARTING PULLDOWN'
    for a in Artist.objects.all():
        print '  %s' % (a.name,)
        scraper.info_for_artist(a.name, a)
        scraper.albums_for_artist(a.name, a)
    print 'ENDING PULLDOWN'
    artist_thread = None
def get_artist_data(req):
    global artist_thread
    artist_thread = threading.Thread(target=reload_artists)
    artist_thread.setDaemon(True)
    artist_thread.start()
    return redirect('/')

def view_artist(req, n):
    a = Artist.objects.get(slug=n)
    scraper.info_for_artist(a.name, a)
    scraper.albums_for_artist(a.name, a)
    return tmpl('artist.html', artist=a)

ui/templates/albums.html
{% extends "base.html" %}

{% block body %}

{% for b in albums.all|dictsortreversed:"allmusic_pick"|dictsortreversed:"combinedscore" %}
    <p><a href="/artist/{{ b.artist.slug }}/album/{{ b.slug }}">{{ b.name }}</a>

        <!--
        &mdash; {{ b.allmusic_rating }} {% if b.allmusic_pick %}✓{% endif %}
        &mdash; rat {{ b.rym_rating }} / pop {{ b.rym_popularity }} / over {{ b.rym_overall }}
    -->
        &ndash; {{ b.combinedscore }} {% if b.allmusic_pick %}✓{% endif %}
    </p>
{% empty %}
    <p>You don't have any albums yet</p>
{% endfor %}

{% endblock %}

ui/templates/artist.html
{% extends "base.html" %}

{% block body %}

<h2>{{ artist.name }}</h2>

{% for b in artist.album_set.all|dictsortreversed:"allmusic_pick"|dictsortreversed:"combinedscore" %}
    <p><a href="/artist/{{ artist.slug }}/album/{{ b.slug }}">{{ b.name }}</a>
        
        <!--
        &mdash; {{ b.allmusic_rating }} {% if b.allmusic_pick %}✓{% endif %}
        &mdash; rat {{ b.rym_rating }} / pop {{ b.rym_popularity }} / over {{ b.rym_overall }}
    -->
        &ndash; {{ b.combinedscore }} {% if b.allmusic_pick %}✓{% endif %}
    </p>
{% empty %}
    <p>They don't have any albums yet</p>
{% endfor %}

<hr>

<p>{{ artist.allmusic_bio|safe }}</p>

{% endblock %}

ui/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>

    <link href="style.css" rel="stylesheet" type="text/css">

</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

ui/templates/home.html
{% extends "base.html" %}

{% block body %}

<p><form action="get-artist-data" method="post" accept-charset="utf-8">
    Get data for artists (may take a while)
    <input type="submit">
</form></p>

<hr>

{% for a in artists %}
    <p><a href="artist/{{ a.slug }}">{{ a.name }}</a> &mdash; {{ a.allmusic_bio|safe|truncatewords_html:20 }}</p>
    
{% empty %}
    <p>You don't have any artists</p>
{% endfor %}
<p><form action="artist/add" method="post" accept-charset="utf-8">
    <label for='name'>Add artist named: </label>
    <input type="text" name="name" value="Metallica">
    <input type="submit" value="Add">
</form></p>

<hr>

<p><form action="lastfm-import" method="post" accept-charset="utf-8">
    <label for='name'>Import from last.fm: </label>
    <input type="text" name="name" placeholder="username">
    <input type="submit" value="Import">
</form></p>

{% endblock %}

ui/templates/lastfm_artist_importer.html
{% extends "base.html" %}

{% block body %}

<form action="lastfm-import-artists" method="post" accept-charset="utf-8">
{% for a in artistnames %}
    <p>
        <input type="checkbox" name="{{a}}" checked="checked">
        <label for='{{a}}'>{{a}}</label>
    </p>
{% endfor %}
    <p><input type="submit" value="Add"></p>
</form>

{% endblock %}